# Generated by Django 5.2.14 on 2026-07-07 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('wechat', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('source_label', models.CharField(blank=True, max_length=80)),
                ('stage', models.CharField(choices=[('new_lead', 'New lead'), ('qualified', 'Qualified'), ('contacted', 'Contacted'), ('invited', 'Invited'), ('test_drive_booked', 'Test drive booked'), ('test_driven', 'Test driven'), ('quoted', 'Quoted'), ('deposit_paid', 'Deposit paid'), ('contract_signed', 'Contract signed'), ('delivered', 'Delivered'), ('lost', 'Lost')], default='new_lead', max_length=32)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('deal_probability', models.PositiveSmallIntegerField(default=0)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('next_action_due_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='tenants.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('task_type', models.CharField(blank=True, max_length=60)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='customers.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('energy_type', models.CharField(blank=True, max_length=40)),
                ('body_type', models.CharField(blank=True, max_length=40)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preferred_brands', models.JSONField(blank=True, default=list)),
                ('preferred_models', models.JSONField(blank=True, default=list)),
                ('usage_scenario', models.CharField(blank=True, max_length=120)),
                ('payment_preference', models.CharField(blank=True, max_length=80)),
                ('trade_in_intent', models.BooleanField(default=False)),
                ('purchase_timeline', models.CharField(blank=True, max_length=80)),
                ('key_concerns', models.JSONField(blank=True, default=list)),
                ('competitor_models', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demand_profile', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('wechat', 'Wechat'), ('phone', 'Phone'), ('store_visit', 'Store visit'), ('website', 'Website'), ('other', 'Other')], default='other', max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('summary', models.TextField()),
                ('raw_content', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customers.customer')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'stage'], name='customers_c_tenant__33459d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'),
        ),
    ]
