# Generated by Django 5.2.14 on 2026-07-11 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_level', models.CharField(choices=[('n', 'N'), ('d', 'D'), ('c', 'C'), ('b', 'B'), ('a', 'A'), ('a_plus', 'A+')], max_length=16)),
                ('new_level', models.CharField(choices=[('n', 'N'), ('d', 'D'), ('c', 'C'), ('b', 'B'), ('a', 'A'), ('a_plus', 'A+')], max_length=16)),
                ('old_score', models.PositiveSmallIntegerField()),
                ('new_score', models.PositiveSmallIntegerField()),
                ('trigger', models.CharField(max_length=120)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('scoring_version', models.CharField(default='v1', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_level',
            field=models.CharField(choices=[('n', 'N'), ('d', 'D'), ('c', 'C'), ('b', 'B'), ('a', 'A'), ('a_plus', 'A+')], default='n', max_length=16),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='level_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='level_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='customer',
            name='level_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customer',
            name='scoring_version',
            field=models.CharField(default='v1', max_length=16),
        ),
        migrations.AddField(
            model_name='demandprofile',
            name='purchase_timeline_bucket',
            field=models.CharField(blank=True, choices=[('within_7_days', 'Within 7 days'), ('8_to_15_days', '8 to 15 days'), ('16_to_30_days', '16 to 30 days'), ('31_to_60_days', '31 to 60 days'), ('61_to_90_days', '61 to 90 days'), ('over_90_days', 'Over 90 days')], default='', max_length=24),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'level_status', 'customer_level'], name='customers_c_tenant__27057a_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('customer_score__gte', 0), ('customer_score__lte', 100)), name='customer_score_between_0_and_100'),
        ),
        migrations.AddField(
            model_name='customerlevelhistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_level_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerlevelhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_history', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='customerlevelhistory',
            index=models.Index(fields=['customer', 'created_at'], name='customers_c_custome_dee492_idx'),
        ),
    ]
