# Generated by Django 5.2.14 on 2026-07-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
