# Generated by Django 5.2.14 on 2026-07-07 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('country', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('model_year', models.PositiveSmallIntegerField()),
                ('body_type', models.CharField(blank=True, max_length=60)),
                ('energy_type', models.CharField(choices=[('ice', 'Fuel'), ('bev', 'Battery electric'), ('phev', 'Plug-in hybrid'), ('hev', 'Hybrid'), ('erev', 'Range extended')], default='bev', max_length=24)),
                ('seats', models.PositiveSmallIntegerField(default=5)),
                ('guide_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('guide_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('competitor_models', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['series__brand__name', 'series__name', '-model_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalesPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_type', models.CharField(choices=[('cash_discount', 'Cash discount'), ('finance', 'Finance'), ('insurance', 'Insurance'), ('trade_in', 'Trade in'), ('accessory', 'Accessory')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_policies', to='tenants.store')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_policies', to='vehicles.vehiclemodel')),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='vehicles.brand')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehicleseries'),
        ),
        migrations.CreateModel(
            name='VehicleTrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('official_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('range_km', models.PositiveIntegerField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='vehicles.vehiclemodel')),
            ],
            options={
                'ordering': ['model', 'official_price'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vin', models.CharField(max_length=32, unique=True)),
                ('exterior_color', models.CharField(blank=True, max_length=80)),
                ('interior_color', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('in_transit', 'In transit'), ('test_drive', 'Test drive')], default='available', max_length=24)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('listed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('negotiable_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mileage_km', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_inventory', to='tenants.store')),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='vehicles.vehicletrim')),
            ],
            options={
                'ordering': ['status', 'arrival_date', 'trim__model__name'],
                'indexes': [models.Index(fields=['store', 'status'], name='vehicles_ve_store_i_43cd9b_idx'), models.Index(fields=['vin'], name='vehicles_ve_vin_051ceb_idx')],
            },
        ),
    ]
